---
title: "Processo"
subtitle: "ESRSF286"
author: "pbrunier@cogne.com"
version: 1.0 
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    css: ./custom.css
    df_print: paged
    gallery: no
    highlight: default
    html_document: null
    lightbox: yes
    number_sections: yes
    self_contained: yes
    thumbnails: no
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      fig.height = 7,
                      fig.width = 10,
                      collapse = TRUE,
                      cols.print=20)
rm(list = ls(all.names = TRUE))
require(dplyr)
require(rlang)
require(kableExtra)
require(readr)
require(ggplot2)
source('~/dev/ESRSF286/R/function.R')
```


# Processo

Nel 2020 i CND segnalano l'aumento del sospeso al collaudo UT sul prodotto laminato al TBB o sul fucinato della marca **SF286** rifuso ESR. La prevalente causale della sospensione è per difetti fuori asse (freckles). Il materiale sospeso e che risulta avere FBH > 2 viene deviato in barre. Un deviato al collaudo UT elevato può causare ritardi alla laminazione in vergella e nei casi peggiori mancanza di materiale per soddisfare l'ordine cliente.

A seguito di tale segnalazione, è stata avviata una raccolta dati sul collaudo ultrasuoni e sul processo. 

I dati di processo raccolti sono relativi all'analisi chimica della colata madre AOD e ai dati di rifusione ESR. Verranno pertanto trascurati i parametri dei processi di trasformazione termo-meccanica a valle della rifusione ESR, perchè ritenuti ininfluenti sulla formazione dei freckles.

I dati del collaudo ultrasuoni sono stati estratti da Qlik e fanno riferimento alle schede testate. Ogni scheda corrisponde ad una colata ESR. Più colate ESR corrispondono ad una colata AOD. Il numero di schede per colata AOD è omogeneo.

Per riassumere i dati di processo:

+ Ogni colata AOD ha una propria analisi chimica
+ Ogni colata AOD genera N colate ESR
+ Ogni colata ESR genera una scheda