---
title: "Data Preparation "
subtitle: "ESRSF286"
author: "pbrunier@cogne.com"
version: 1.0 
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    css: ./custom.css
    df_print: paged
    gallery: no
    highlight: default
    html_document: null
    lightbox: yes
    number_sections: yes
    self_contained: yes
    thumbnails: no
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      error = FALSE,
                      fig.height = 7,
                      fig.width = 10,
                      collapse = TRUE,
                      cols.print=20)
rm(list = ls(all.names = TRUE))

require(dplyr)
require(kableExtra)
require(readr)
require(reticulate)

source('~/dev/ESRSF286/R/function.R')
```

# Dati per odp

Importiamo il file header.csv


```{r header_load}
header <- read_delim('/data/ESRSF286/header/header_ESRSF286_R.csv', 
                     delim=';',
                     col_type=cols())


```


estraiamo i colnames ed i coltypes dall'header

```{r estraction_info}
col_name <- header %>% 
  pull(col_name)

col_type <- header %>%
  pull(data_type)
```

leggiamo i dati 

```{r read_data}
datiSF <- read_delim('/data/ESRSF286/dati_SF286_2020_2021.csv',
                          delim = ';',
                          skip = 1,
                          col_names = col_name,
                          col_types = col_type,
                          n_max = Inf)

```

aggiungiamo la colonna scarto_perc, intesa come

$sc_{perc} = kg_{deviato} / kg_{impiegato} *100$

```{r scarto}
datiSF <- datiSF %>%
  filter(kg_impiegato > 0.)
  

datiSF <- datiSF %>%
  mutate(sc_perc = kg_deviato/kg_impiegato *100)
```

aggiungiamo la colonna energia_tot, intesa come

$E_{ESR} = \frac{metling rate}{melting power} /1e3 [kW]$

```{r energia}
datiSF <- datiSF %>%
  filter(melting_power > 1)

datiSF <- datiSF %>%
  mutate(energia = melting_rate/melting_power/1000)
```

riordino variabili

```{r ordering}
datiSF <- datiSF %>% 
  select(odp,colata_madre,data_collaudo,colata_esr,data_esr,cdl,ese,sc_perc,
         anomalie_ESR,
         everything())
```

aggiugo indici di riga nella prima colonna

```{r indexing}
datiSF <- datiSF %>% 
  mutate(index = row_number()) %>% 
  select(index, everything())
```



salva rds

```{r saving_rds}
write_rds(datiSF,'/data/ESRSF286/ESRSF286.rds')
```

```{r passing_variable}

py$df <- datiSF
```

```{python saving_pkl}

import pandas as pd

df = pd.DataFrame(df)
df.to_pickle('/data/ESRSF286/ESRSF286.pkl')

```
